- name: create backend directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: copy backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: unpack backend files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start app
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env
